### ISSUE TITLE
API Stability and versioning strategy

### ISSUE THREAD

**Issue by kylelaker** [usnistgov/liboscal-java#116]
In v1.0.4.3, we were able to import `Party` as `gov.nist.secauto.oscal.lib.model.Party`. In v1.0.4.4, that symbol no longer exists (it looks like it's now `gov.nist.secauto.oscal.lib.model.Metadata.Party` based on #109).

v1.0.4.4 did not have release notes (or a "[Release](https://github.com/usnistgov/liboscal-java/releases)" object) on GitHub like previous releases (I think this at least is covered by #113), so there wasn't any clean set of changes to review (in fact, Dependabot just gave us a [list of commits](https://github.com/EasyDynamics/oscal-rest-service/pull/167)).

In general, I think nearly half of all updates since 1.0.2 have included API-breaking changes (whether due to the OSCAL submodule, as in #109) or internal `metaschema-java` related changes (such as JSON marshaling). Are there specific things that library consumers can look out for, on this repo, OSCAL, or `metaschema-java` to know if a change to `liboscal-java` may feature an API-breaking change?

Generally, it's not a big problem for us to adapt to minor changes; however, it is nice to have context and an easy-to-identify cause to get a better feel for how to adapt to the new API.

**Comment by aj-stein-nist** [comment]
@kylelaker thank you so much for the feedback. I am incrementally assuming maintainer rights on this repo and will need to address a lot of these concerns myself. This time, I dropped the ball working through a bug resolution fix and this change cropped up last minute as I was locally preparing the release with the Maven command. Moving forward, I will commit to the semver guarantee I have no doubt is documented here. Additionally, I should have known better but forgot you are a key outside consumer of the interfaces in liboscal-java and oscal-cli exclusively.

So, moving forward:

1. Clearer documentation.
2. Stronger enforcement of API stability guarantees, per 1.
3. Longer pre-releases windows, even if there are urgent bug fixes.

I had let some issues languist in usnistgov/oscal-cli#70 languish, so there was a lot of hurry up after waiting, and that impacted you negatively. That cannot happen again, and you will be right to call me out more aggressively if it does. :-)

Thanks for the report. I will potentially convert it from a question into one or more relevant issues when I have time to breaths. Talk soon (hopefully)!

**Comment by aj-stein-nist** [comment]
I do apologize again for the trouble caused with this release. I also realized that release notes were not formalized, nor the release itself, for v1.0.4.4. That has now been updated.

https://github.com/usnistgov/liboscal-java/releases/tag/v1.0.4.4

In the future, maintenance of SemVer guarantees will be stronger and this will be the last ex post facto release and release notes. I had not even noticed that I hadn't formalized the release until some cleanup this morning. If you feel beyond these comments we can do something to address that more specifically, please feel free to re-open the issue.
