### ISSUE TITLE
Build and deploy liboscal-java Javadoc

### ISSUE THREAD

**Issue by kylelaker** [usnistgov/liboscal-java#130]
# User Story:

As a `liboscal-java` API consumer, I want to have Javadoc available to understand the API of both custom classes in this library as well as the code automatically generated from the metaschema assemblies.

It looks like this is already done in `metaschema-java` for its API; hopefully a similar pattern could be used for this library?

## Goals:

- Javadoc is generated as part of the build process
- Documentation is available in a web browser (possibly at pages.nist.gov like for `metaschema-java`?)

## Acceptance Criteria

- [x] All website and readme documentation affected by the changes in this issue have been updated.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
Thanks, this is a good catch. I will look into this.

**Comment by aj-stein-nist** [comment]
@aj-stein-nist needs to coordinate with @david-waltermire-nist to test the configuration and work through issues before turning it back on.

**Comment by aj-stein-nist** [comment]
This was released as part of 2.0.0. Please review the following API reference pages.

https://pages.nist.gov/liboscal-java/xref/index.html
