### ISSUE TITLE
Oscal-cli  -Validastion is throwing an error oscal-cli version 0.3.4-SNAPSHOT

### ISSUE THREAD

**Issue by ThomAPenn** [usnistgov/liboscal-java#141]
# Describe the bug

Validation is throwing an error. It actually appears to return values but it is probably a org.xml.sax.SAXParseException.

[97m[[0;91mERROR[0;97m] [mcvc-pattern-valid: Value '2022-12-04T16:53:07.175494800-05:00' is not facet-valid with respect to pattern '(((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)|(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))|(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))|(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30)))T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]*[1-9])?(Z|(-((0[0-9]|1[0-2]):00|0[39]:30)|\+((0[0-9]|1[0-4]):00|(0[34569]|10):30|(0[58]|12):45)))?' for type 'oscal-metadata-last-modified-FIELD'. [file:///home/AwesomeCloudSSP2.xml{8,75}]
org.xml.sax.SAXParseException: cvc-pattern-valid: Value '2022-12-04T16:53:07.175494800-05:00' is not facet-valid with respect to pattern '(((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)|(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))|(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))|(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30)))T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]*[1-9])?(Z|(-((0[0-9]|1[0-2]):00|0[39]:30)|\+((0[0-9]|1[0-4]):00|(0[34569]|10):30|(0[58]|12):45)))?' for type 'oscal-metadata-last-modified-FIELD'.

# Who is the bug affecting?
oscal-cli version 0.3.4-SNAPSHOT built on 2023-05-15 13:09 on commit a39d0b0
OSCAL version @oscal-git.closest.tag.name@ on commit @oscal-git.commit.id.abbrev@

# What is affected by this bug?
Oscal-cli Validations

# How do we replicate the issue?
oscal-cli ssp validate –as xml AwesomeCloudSSP2.xml 

# Expected behavior (i.e. solution)

To show validation from the cli to of SSP 

# Other Comments

**Comment by david-waltermire-nist** [comment]
The [updated test for this](https://github.com/usnistgov/metaschema-java/blob/develop/metaschema-model-common/src/test/java/gov/nist/secauto/metaschema/model/common/datatype/adapter/DateTimeAdapterTest.java) is in metaschema-java. It includes fractional seconds with trailing zeros, proving this issue is fixed.

**Comment by aj-stein-nist** [comment]
This should now be resolved in the 2.0.0 release from this evening and a pending oscal-cli update. Closing.
