### ISSUE TITLE
Profile resolution fails when removing a control's nested part

### ISSUE THREAD

**Issue by Rene2mt** [usnistgov/liboscal-java#59]
# Describe the bug

In a profile, trying to remove a control's nested part throws an error stating _'Unable to apply the remove targeting control "control-id"  at "xpath to remove element".  The remove did not match a valid tag'_.  This error occurs when attempting to resolve profiles.

# Who is the bug affecting?
OSCAL-CLI users 

# What is affected by this bug?

Cannot resolve profile.

# When does this occur?

OSCAL-CLI users when trying to resolve a profile but remove sub-parts of a control. 

# How do we replicate the issue?

1.  Use a profile that attempts to remove a control's nested part (e.g. FedRAMP rev 4 LI-SaaS baseline - see https://github.com/GSA/fedramp-automation/blob/2229f10cc0b143410522026b793f4947eebb0872/dist/content/baselines/rev4/xml/FedRAMP_rev4_LI-SaaS-baseline_profile.xml#L514 )
2. Attempt to resolve the profile as follows:
```
rene2mt@1556552G-M30682:/mnt/c/oscal-cli/oscal-cli-0.2.0/bin$ ./oscal-cli profile resolve -t=xml /mnt/c/fedramp-automation/src/content/baselines/rev4/xml/FedRAMP_rev4_LI-SaaS-baseline_profile.xml > test.xml
Unable to resolve profile 'file:///mnt/c/fedramp-automation/src/content/baselines/rev4/xml/FedRAMP_rev4_LI-SaaS-baseline_profile.xml'. Unable to apply the remove targeting control 'ac-2' at '/profile/modify[1]/alter[2]/remove[1]'. The remove did not match a valid target
rene2mt@1556552G-M30682:/mnt/c/oscal-cli/oscal-cli-0.2.0/bin$ 
```

# Expected behavior (i.e. solution)

Profile should resolve with specified control's parts (and/or sub-parts) removed.  For example, the following would be removed from the resolved profile.
```
<remove by-id="ac-2_smt.b"/>
```

# Other Comments

The same profile(s) that cause error with the OSCAL-CLI resolve successfully with the build-cli.

**Comment by david-waltermire-nist** [comment]
@Rene2mt Here is an [interim build](https://github.com/usnistgov/liboscal-java/files/9389828/cli-core-0.2.0-SNAPSHOT-oscal-cli.zip) that fixes this issue. Please confirm.

**Comment by Rene2mt** [comment]
The fix worked
