### ISSUE TITLE
Improper handling of group links during profile resolution

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/liboscal-java#65]
# Describe the bug

When using a profile, such as the [ARS moderate profile](https://github.com/CMSgov/ars-machine-readable/blob/4850049d550772672be855c5551a727aa57eb1bd/ODP-extract/ars-5.0-moderate-profile.xml), oscal-cli produces the following errors.

> ```
> the anchor should reference a resource, control, group, or part identified by 'ir', but the identifier was not found in the index.
> the anchor should reference a resource, control, group, or part identified by 'pe', but the identifier was not found in the index.
> the anchor should reference a resource, control, group, or part identified by 'mp', but the identifier was not found in the index.
> ```

This is due to the three references (in `<a>` elements) in the catalog which target `group` elements. The groups are removed since the structuring directive `flat` is used.

# Who is the bug affecting?

Users of the oscal-cli tool and this library performing profile resolution.

# What is affected by this bug?

Any profile using the `flat` structuring directive with a group reference.

# When does this occur?

See above.

# How do we replicate the issue?

See above.

# Expected behavior (i.e. solution)

Links to groups should be resolved to absolute URLs pointing to the original catalog, replacing the current links.

# Other Comments

None.

**Comment by GaryGapinski** [comment]
Added explicit `/profile/merge/as-is` in https://github.com/CMSgov/ars-machine-readable/pull/34/commits/6b1c4d2699b22e95fbac016a881f6dec03f1e62f but problem persists (resolved catalog lacks control groups).

**Comment by david-waltermire-nist** [comment]
@GaryGapinski and @openprivacy Try the following build. According to my unit tests, I believe this issue is fixed.

[cli-core-0.2.1-SNAPSHOT-oscal-cli.zip](https://github.com/usnistgov/liboscal-java/files/9536141/cli-core-0.2.1-SNAPSHOT-oscal-cli.zip)

**Comment by openprivacy** [comment]
cli-core-0.2.1-SNAPSHOT fixes the issue (no more warnings) but I was surprised at the number of additional ODPs that popped up (see attachment
[diff_ars-5.0-moderate-catalog.txt](https://github.com/usnistgov/liboscal-java/files/9537436/diff_ars-5.0-moderate-catalog.txt))
 not yet sure if that was to be expected.

**Comment by david-waltermire-nist** [comment]
@openprivacy  The resolver was not processing some nodes previously causing spurious results due to a number of issues which have been corrected in the latest. This could explain why some parameters were previously ignored.

Let me know if you see anything that is out of place.

**Comment by GaryGapinski** [comment]
I tried that build with this profile and saw no error messages.
```
gapinski@flexion-mac-C02FCBVSMD6N ODP-extract % alias oscal-cli=/Users/gapinski/tmp/oscal-cli/bin/oscal-cli                                 
gapinski@flexion-mac-C02FCBVSMD6N ODP-extract % oscal-cli --version                                                                         
oscal-cli version 0.2.1-SNAPSHOT built on 2022-09-09 13:59 on commit fc06df7
OSCAL version v1.0.4 on commit c4de2fe

gapinski@flexion-mac-C02FCBVSMD6N ODP-extract % oscal-cli profile resolve ars-5.0-moderate-profile.xml ars-5.0-moderate-profile-resolved.xml

gapinski@flexion-mac-C02FCBVSMD6N ODP-extract %
```
That profile has
```
    <merge>
        <as-is/>
    </merge>
```
The output resolved profile contained all groups. All selected controls (352) and parameter values (568) were present in the resolved profile.

If the `merge` element with its `asis` is removed, the group are removed and the references are qualified as
```
<a href="file:/Users/gapinski/Projects/github/GaryGapinski/ars-machine-readable/ODP-extract/ars-5.0-catalog.xml#pe">PE</a>
```

**Comment by xee5ch** [comment]
I can confirm I was able to recreate the same behavior as reported by @GaryGapinski  in https://github.com/usnistgov/liboscal-java/issues/65#issuecomment-1243609958 with the snapshot release provided in https://github.com/usnistgov/liboscal-java/issues/65#issuecomment-1242029523.
